"""sendgrid implementation to verify email

Revision ID: 35007eadbfb3
Revises: a6efb50128cc
Create Date: 2025-08-31 17:49:31.447028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35007eadbfb3'
down_revision: Union[str, None] = 'a6efb50128cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_email_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_email_sent')
    # ### end Alembic commands ###
