"""Initial migration

Revision ID: 9fbd64cca8c7
Revises: eaba50222738
Create Date: 2025-08-25 16:28:37.171357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbd64cca8c7'
down_revision: Union[str, None] = 'eaba50222738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('community_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'posts', 'communities', ['community_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'community_id')
    # ### end Alembic commands ###
