"""Add google auth fields

Revision ID: a6efb50128cc
Revises: f2c33d2254ff
Create Date: 2025-08-31 15:07:15.261014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6efb50128cc'
down_revision: Union[str, None] = 'f2c33d2254ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add google_id as nullable (this is fine)
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    
    # Add is_email_verified as nullable first
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    
    # Set default value for existing users
    op.execute("UPDATE users SET is_email_verified = false WHERE is_email_verified IS NULL")
    
    # Now make it NOT NULL
    op.alter_column('users', 'is_email_verified', nullable=False)
    
    # Create the unique index for google_id
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
