"""added role in user model

Revision ID: ee08afc99d5c
Revises: 9fbd64cca8c7
Create Date: 2025-08-29 13:23:44.255083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee08afc99d5c'
down_revision: Union[str, None] = '9fbd64cca8c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_community', 'community_members', ['user_id', 'community_id'])
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint('unique_user_community', 'community_members', type_='unique')
    # ### end Alembic commands ###
